[build]
{% case board -%}
  {%- when "Adafruit Trinket" -%}
    target = "avr-specs/avr-attiny85.json"
  {%- when "Adafruit Trinket Pro" -%}
    target = "avr-specs/avr-atmega328p.json"
  {%- when "Arduino Leonardo" -%}
    target = "avr-specs/avr-atmega32u4.json"
  {%- when "Arduino Mega 2560" -%}
    target = "avr-specs/avr-atmega2560.json"
  {%- when "Arduino Mega 1280" -%}
    target = "avr-specs/avr-atmega1280.json"
  {%- when "Arduino Nano" -%}
    target = "avr-specs/avr-atmega328p.json"
  {%- when "Arduino Nano New Bootloader" -%}
    target = "avr-specs/avr-atmega328p.json"
  {%- when "Arduino Uno" -%}
    target = "avr-specs/avr-atmega328p.json"
  {%- when "SparkFun ProMicro" -%}
    target = "avr-specs/avr-atmega32u4.json"
  {%- when "SparkFun ProMini 3v3" -%}
    target = "avr-specs/avr-atmega328p.json"
  {%- when "SparkFun ProMini 5v" -%}
    target = "avr-specs/avr-atmega328p.json"
  {%- when "Nano168" -%}
    target = "avr-specs/avr-atmega168.json"
{%- endcase %}

[target.'cfg(target_arch = "avr")']
runner = "ravedude"

[unstable]
build-std = ["core"]
{%- comment %}
# vim: ft=toml.jinja2
{% endcomment %}
